#!/usr/bin/env bash

# mpc (and mpd) seem to have trouble with complex filenames. still working on a solution to this
# relative path to mpd's music directory *must* be used. absolute path will not be read by mpd.

file="$(mpc listall | wofi --dmenu)" || exit 0

notify-send "Playing $file" && mpc insert "$file" && mpc next >/dev/null
